#!/usr/bin/env bash

set -eu

export OBS="obs"
export GEN="gen"
export MODEL="a.model"

prelude () {
    cd $WD/model/data/
    if [ ! -f "$OBS.csv" ]; then
        cat $WD/sql/shots.sql | sqlite3 -csv $WD/ruskie.db > "$OBS.csv"
    fi
    if [ ! -f "$GEN.libsvm" ]; then
        python ../scripts/generate.py "$GEN.csv"
    fi
    python ../scripts/convert.py "$OBS.csv" "$OBS.libsvm"
    head -n 25000 $OBS.libsvm > train.libsvm
    tail -n+25001 $OBS.libsvm > test.libsvm
    python ../scripts/convert.py "$GEN.csv" "$GEN.libsvm"
}

interlude () {
    cd $WD/model/
    $WD/xgboost/xgboost train.conf model_out="out/$MODEL"
    $WD/xgboost/xgboost \
        train.conf \
        test:data="data/$GEN.libsvm" \
        model_in="out/$MODEL" \
        task=pred \
        name_pred="out/pred.csv"
}

postlude () {
    python scripts/plot.py
    if [ $(uname -s) = "Darwin" ]; then
        open out/plot.png
    else
        xdg-open out/plot.png
    fi
}

main () {
    prelude
    interlude
    postlude
}

main
