#!/usr/bin/env bash

if [ -z $1 ]; then
    flag=""
else
    flag=$1
fi

set -eu

prelude () {
    clippy
    cargo test -q --bin games
    rustfmts
    if [ "$flag" = "debug" ]; then
        cargo build
    else
        cargo build --release
    fi
}

interlude () {
    f () {
        export START=$1
        export END=$2
        if [ "$flag" = "debug" ]; then
            cargo run --bin schedule
        else
            cargo run --bin schedule --release
        fi
    }

    x="$WD/data/teams.json"
    if [ ! -f $x ]; then
        curl "https://statsapi.web.nhl.com/api/v1/teams" > $x
    fi
    if [ "$flag" = "debug" ]; then
        cargo run --bin teams
    else
        cargo run --bin teams --release
    fi
    f "2017-08-01" "2018-08-01"
    f "2018-08-01" "2019-08-01"
    if [ "$flag" = "debug" ]; then
        cargo run --bin games
    else
        cargo run --bin games --release
    fi
}

postlude () {
    f () {
        printf "\nsql $1\n"
        rlwrap sqlite3 --column --header $WD/ruskie.db "$1"
    }

    for x in teams schedule; do
        f "SELECT COUNT(*) FROM $x;"
        f "SELECT COUNT(DISTINCT id) FROM $x;"
    done
    for x in players events shifts; do
        f "SELECT COUNT(*) FROM $x"
        f "SELECT COUNT(DISTINCT game_id) FROM $x;"
    done
    for x in events shifts; do
        f "SELECT COUNT(DISTINCT player_id) FROM $x;"
    done
}

main () {
    cd $WD/dev
    prelude
    interlude
    postlude
}

main
